version: 2

project_name: mudora

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/mudora
    binary: mudora
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/alttpr-mudora/mudora/internal.Version={{ .Version }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  github:
    owner: alttpr-mudora
    name: mudora
