package alttp

var Regions = map[string][]string{
	"Light World": {
		"Sahasrahla's Hut - Left",
		"Sahasrahla's Hut - Middle",
		"Sahasrahla's Hut - Right",
		"Sahasrahla",
		"Zora's Ledge",
		"Waterfall Fairy - Left",
		"Waterfall Fairy - Right",
		"Master Sword Pedestal",
		"King's Tomb",
		"Kakariko Tavern",
		"Chicken House",
		"Kakariko Well - Top",
		"Kakariko Well - Left",
		"Kakariko Well - Middle",
		"Kakariko Well - Right",
		"Kakariko Well - Bottom",
		"Blind's Hideout - Top",
		"Blind's Hideout - Left",
		"Blind's Hideout - Right",
		"Blind's Hideout - Far Left",
		"Blind's Hideout - Far Right",
		"Pegasus Rocks",
		"Bottle Merchant",
		"Magic Bat",
		"Lost Woods Hideout",
		"Lumberjack Tree",
		"Graveyard Ledge",
		"Mushroom",
		"Floodgate Chest",
		"Link's House",
		"Aginah's Cave",
		"Mini Moldorm Cave - Far Left",
		"Mini Moldorm Cave - Left",
		"Mini Moldorm Cave - Right",
		"Mini Moldorm Cave - Far Right",
		"Ice Rod Cave",
		"Hobo",
		"Cave 45",
		"Checkerboard Cave",
		"Mini Moldorm Cave - NPC",
		"Library",
		"Maze Race",
		"Desert Ledge",
		"Lake Hylia Island",
		"Sunken Treasure",
	},
	"Hyrule Castle": {
		"Sanctuary",
		"Sewers - Secret Room - Left",
		"Sewers - Secret Room - Middle",
		"Sewers - Secret Room - Right",
		"Sewers - Dark Cross",
		"Hyrule Castle - Boomerang Chest",
		"Hyrule Castle - Map Chest",
		"Hyrule Castle - Zelda's Cell",
		"Secret Passage",
	},
	"Eastern Palace": {
		"Eastern Palace - Compass Chest",
		"Eastern Palace - Big Chest",
		"Eastern Palace - Cannonball Chest",
		"Eastern Palace - Big Key Chest",
		"Eastern Palace - Map Chest",
		"Eastern Palace - Boss",
	},
	"Desert Palace": {
		"Desert Palace - Big Chest",
		"Desert Palace - Map Chest",
		"Desert Palace - Torch",
		"Desert Palace - Big Key Chest",
		"Desert Palace - Compass Chest",
		"Desert Palace - Boss",
	},
	"Death Mountain": {
		"Old Man",
		"Spectacle Rock Cave",
		"Spectacle Rock",
		"Spiral Cave",
		"Mimic Cave",
		"Paradox Cave Lower - Far Left",
		"Paradox Cave Lower - Left",
		"Paradox Cave Lower - Right",
		"Paradox Cave Lower - Far Right",
		"Paradox Cave Lower - Middle",
		"Paradox Cave Upper - Left",
		"Paradox Cave Upper - Right",
		"Floating Island",
	},
	"Tower of Hera": {
		"Tower of Hera - Big Key Chest",
		"Tower of Hera - Map Chest",
		"Tower of Hera - Compass Chest",
		"Tower of Hera - Big Chest",
		"Tower of Hera - Boss",
	},
	"Castle Tower": {
		"Castle Tower - Room 03",
		"Castle Tower - Dark Maze",
	},
	"Dark World": {
		"Superbunny Cave - Top",
		"Superbunny Cave - Bottom",
		"Hookshot Cave - Top Right",
		"Hookshot Cave - Top Left",
		"Hookshot Cave - Bottom Left",
		"Hookshot Cave - Bottom Right",
		"Spike Cave",
		"Catfish",
		"Pyramid",
		"Pyramid Fairy - Left",
		"Pyramid Fairy - Right",
		"Pyramid Fairy - Bow",
		"Pyramid Fairy - Sword",
		"Brewery",
		"C-Shaped House",
		"Chest Game",
		"Hammer Pegs",
		"Bumper Cave",
		"Purple Chest",
		"Hype Cave - Top",
		"Hype Cave - Middle Right",
		"Hype Cave - Middle Left",
		"Hype Cave - Bottom",
		"Stumpy",
		"Hype Cave - NPC",
		"Digging Game",
		"Mire Shed - Left",
		"Mire Shed - Right",
	},
	"Palace of Darkness": {
		"Palace of Darkness - Shooter Room",
		"Palace of Darkness - Big Key Chest",
		"Palace of Darkness - The Arena - Ledge",
		"Palace of Darkness - The Arena - Bridge",
		"Palace of Darkness - Stalfos Basement",
		"Palace of Darkness - Map Chest",
		"Palace of Darkness - Big Chest",
		"Palace of Darkness - Compass Chest",
		"Palace of Darkness - Harmless Hellway",
		"Palace of Darkness - Dark Basement - Left",
		"Palace of Darkness - Dark Basement - Right",
		"Palace of Darkness - Dark Maze - Top",
		"Palace of Darkness - Dark Maze - Bottom",
		"Palace of Darkness - Boss",
	},
	"Swamp Palace": {
		"Swamp Palace - Entrance",
		"Swamp Palace - Big Chest",
		"Swamp Palace - Big Key Chest",
		"Swamp Palace - Map Chest",
		"Swamp Palace - West Chest",
		"Swamp Palace - Compass Chest",
		"Swamp Palace - Flooded Room - Left",
		"Swamp Palace - Flooded Room - Right",
		"Swamp Palace - Waterfall Room",
		"Swamp Palace - Boss",
	},
	"Skull Woods": {
		"Skull Woods - Big Chest",
		"Skull Woods - Big Key Chest",
		"Skull Woods - Compass Chest",
		"Skull Woods - Map Chest",
		"Skull Woods - Bridge Room",
		"Skull Woods - Pot Prison",
		"Skull Woods - Pinball Room",
		"Skull Woods - Boss",
	},
	"Thieves' Town": {
		"Thieves' Town - Attic",
		"Thieves' Town - Big Key Chest",
		"Thieves' Town - Map Chest",
		"Thieves' Town - Compass Chest",
		"Thieves' Town - Ambush Chest",
		"Thieves' Town - Big Chest",
		"Thieves' Town - Blind's Cell",
		"Thieves' Town - Boss",
	},
	"Ice Palace": {
		"Ice Palace - Big Key Chest",
		"Ice Palace - Compass Chest",
		"Ice Palace - Map Chest",
		"Ice Palace - Spike Room",
		"Ice Palace - Freezor Chest",
		"Ice Palace - Iced T Room",
		"Ice Palace - Big Chest",
		"Ice Palace - Boss",
	},
	"Misery Mire": {
		"Misery Mire - Big Chest",
		"Misery Mire - Main Lobby",
		"Misery Mire - Big Key Chest",
		"Misery Mire - Compass Chest",
		"Misery Mire - Bridge Chest",
		"Misery Mire - Map Chest",
		"Misery Mire - Spike Chest",
		"Misery Mire - Boss",
	},
	"Turtle Rock": {
		"Turtle Rock - Chain Chomps",
		"Turtle Rock - Compass Chest",
		"Turtle Rock - Roller Room - Left",
		"Turtle Rock - Roller Room - Right",
		"Turtle Rock - Big Chest",
		"Turtle Rock - Big Key Chest",
		"Turtle Rock - Crystaroller Room",
		"Turtle Rock - Eye Bridge - Bottom Left",
		"Turtle Rock - Eye Bridge - Bottom Right",
		"Turtle Rock - Eye Bridge - Top Left",
		"Turtle Rock - Eye Bridge - Top Right",
		"Turtle Rock - Boss",
	},
	"Ganon's Tower": {
		"Ganon's Tower - Bob's Torch",
		"Ganon's Tower - DMs Room - Top Left",
		"Ganon's Tower - DMs Room - Top Right",
		"Ganon's Tower - DMs Room - Bottom Left",
		"Ganon's Tower - DMs Room - Bottom Right",
		"Ganon's Tower - Randomizer Room - Top Left",
		"Ganon's Tower - Randomizer Room - Top Right",
		"Ganon's Tower - Randomizer Room - Bottom Left",
		"Ganon's Tower - Randomizer Room - Bottom Right",
		"Ganon's Tower - Firesnake Room",
		"Ganon's Tower - Map Chest",
		"Ganon's Tower - Big Chest",
		"Ganon's Tower - Hope Room - Left",
		"Ganon's Tower - Hope Room - Right",
		"Ganon's Tower - Bob's Chest",
		"Ganon's Tower - Tile Room",
		"Ganon's Tower - Compass Room - Top Left",
		"Ganon's Tower - Compass Room - Top Right",
		"Ganon's Tower - Compass Room - Bottom Left",
		"Ganon's Tower - Compass Room - Bottom Right",
		"Ganon's Tower - Big Key Chest",
		"Ganon's Tower - Big Key Room - Left",
		"Ganon's Tower - Big Key Room - Right",
		"Ganon's Tower - Mini Helmasaur Room - Left",
		"Ganon's Tower - Mini Helmasaur Room - Right",
		"Ganon's Tower - Pre-Moldorm Chest",
		"Ganon's Tower - Moldorm Chest",
	},
	"Special": {
		"Waterfall Bottle",
		"Pyramid Bottle",
	},
}
